name: tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: compile and test
        run: |
          echo "tests"
          pwd

          cd src
          clang --version 2>&1
          clang -Oz -std=gnu2x -s -Wl,--gc-sections,--strip-all,-z,norelro -fno-unwind-tables -Wno-int-conversion -Wl,--entry=__start -fsanitize=address -fsanitize=undefined main.c -o toolkit
          
          ./toolkit || true

          ./toolkit --bench || true
          
          ./toolkit --setuid 12345 || true
          
          ./toolkit --getuid || true
          
          ./toolkit --getlist || true
          
          ./toolkit --sulog || true
          
          ./toolkit --setver || true
          
          ./toolkit --fkuname default default || true
          
          rm toolkit
          gcc --version 2>&1
          gcc -std=gnu2x -Wl,--gc-sections,-z,norelro -fno-unwind-tables -Wl,--entry=__start -fno-strict-aliasing -fmerge-all-constants -Wno-unknown-attributes main.c -Wno-attributes -Wno-int-conversion -o toolkit 2>&1
          
          ./toolkit || true

          ./toolkit --bench || true
          
          ./toolkit --setuid 12345 || true
          
          ./toolkit --getuid || true
          
          ./toolkit --getlist || true
          
          ./toolkit --sulog || true
          
          ./toolkit --setver || true
          
          ./toolkit --fkuname default default || true          
          
          
          rm toolkit
          zig cc --version 2>&1
          zig version 2>&1
          zig cc -target x86_64-linux -s -Oz -Wno-int-conversion -std=gnu2y -static -Wl,--gc-sections,-z,norelro -fno-unwind-tables -Wl,--entry=__start -flto -fmerge-all-constants -Wno-unknown-attributes main.c -o toolkit 2>&1
          
          ./toolkit || true

          ./toolkit --bench || true
          
          ./toolkit --setuid 12345 || true
          
          ./toolkit --getuid || true
          
          ./toolkit --getlist || true
          
          ./toolkit --sulog || true
          
          ./toolkit --setver || true
          
          ./toolkit --fkuname default default || true          
          
